# Task to automatically build `apple/apple/game-porting-toolkit` 
# and put the resulting Cellar into a dmg

name: Build GPTK

on:
  push:
    branches: [ senpai ]
  workflow_dispatch:

jobs:
  build_gptk:
    name: Build GPTK
    strategy:
        matrix:
          flavour: [Vanilla, Vulkan]
    runs-on: macos-13
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install compiler
        run: |
          brew install apple/apple/game-porting-toolkit-compiler
      - if: matrix.flavour == 'Vulkan'
        name: Patch the formula
        run: |
          patch `brew --repo apple/apple`/Formula/game-porting-toolkit.rb < patches/enable-vulkan-sdl.patch
      - name: Patch rpaths
        run: |
          patch `brew --repo apple/apple`/Formula/game-porting-toolkit.rb < patches/whisky-rpath.patch
      - name: Install GPTK
        run: |
          brew install --build-bottle apple/apple/game-porting-toolkit
      - name: Download Apple's GPTK binaries from Apple
        run: |
          wget https://download.developer.apple.com/Developer_Tools/Game_porting_toolkit_1_beta_4/Game_porting_toolkit_1_beta_4.dmg
          hdiutil attach Game_porting_toolkit_1_beta_4.dmg
          ditto /Volumes/Game\ Porting\ Toolkit-1.0/redist/lib/ `brew --prefix game-porting-toolkit`/lib/
          hdiutil detach /Volumes/Game\ Porting\ Toolkit-1.0
      - name: Package GPTK (Harbor)
        run: |
          brew bottle apple/apple/game-porting-toolkit
          mkdir gptk_bottle
          mv *.tar.gz gptk_bottle
          touch gptk_bottle/.keep
          tar -zcvf gptk_bottle.tar.gz gptk_bottle          
      - name: Upload GPTK bottle (Harbor)
        uses: actions/upload-artifact@v3
        with:
          name: GPTK ${{matrix.flavour}} (Harbor)
          path: gptk_bottle.tar.gz
      - name: Package GPTK (Whisky)
        run: |
          ditto `brew --prefix game-porting-toolkit` Libraries/Wine
          touch Libraries/.keep
          rm -rvf Libraries/Wine/include
          rm -rvf Libraries/Wine/INSTALL_RECEIPT.json
          rm -rvf Libraries/Wine/share/man
          find Libraries/Wine/bin -type f -type l -not -name "wine64" -not -name "wine64-preloader" -not -name "wineserver" -delete
          mkdir gptk
          touch gptk/.keep
          tar -zcvf gptk/gptk.tar.gz Libraries
      - name: Upload GPTK (Whisky)
        uses: actions/upload-artifact@v3
        with:
          name: GPTK ${{matrix.flavour}} (Whisky)
          path: gptk
