# Task to automatically build `apple/apple/game-porting-toolkit` 
# and put the resulting Cellar into a dmg

name: Build GPTK
on:
  - workflow_dispatch

jobs:
  build_gptk:
    name: Build GPTK
    strategy:
        matrix:
          flavour: [Vanilla, Vulkan]
    runs-on: macos-13
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install compiler
        run: |
          brew install apple/apple/game-porting-toolkit-compiler
      - if: matrix.flavour == 'Vulkan'
        name: Patch the formula
        run: |
          patch `brew --repo apple/apple`/Formula/game-porting-toolkit.rb < patches/enable-vulkan-sdl.patch
      - name: Install GPTK
        run: |
          brew install --build-bottle apple/apple/game-porting-toolkit
      - name: Package GPTK (Harbor)
        run: |
          brew bottle apple/apple/game-porting-toolkit
          mkdir gptk_bottle
          mv *.tar.gz gptk_bottle
          touch gptk_bottle/.keep
          tar -zcvf gptk_bottle.tar.gz gptk_bottle          
      - name: Upload GPTK bottle (Harbor)
        uses: actions/upload-artifact@v3
        with:
          name: GTPK ${{matrix.flavour}} (Harbor)
          path: gptk_bottle.tar.gz
      - name: Package GPTK (Whisky)
        run: |
          rm -rvf `brew --prefix game-porting-toolkit`/include
          rm -rvf `brew --prefix game-porting-toolkit`/INSTALL_RECEIPT.json
          rm -rvf `brew --prefix game-porting-toolkit`/share/man
          find `brew --prefix game-porting-toolkit`/bin -type f -type l -not -name "wine64" -not -name "wine64-preloader" -not -name "wineserver" -delete
          tar -zcvf gptk.tar.gz `brew --prefix game-porting-toolkit`
      - name: Upload GPTK (Whisky)
        uses: actions/upload-artifact@v3
        with:
          name: GTPK ${{matrix.flavour}} (Whisky)
          path: gptk.tar.gz
